### ISSUE TITLE
currently core version is not set by the build process

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#638] opened 2023-05-23 15:48 UTC
## What happened?

currently core version is reported as v0.0.0 

## What did you expect to happen?

Update build step, extract `github.com/pomerium/pomerium` version from `go.mod` and set ldflags accordingly. 

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by calebdoxsey** [comment] 2024-01-05 16:17
Duplicate of https://github.com/pomerium/ingress-controller/issues/855

**Closed by calebdoxsey** 2024-01-05 16:17 UTC
Labels: bug, ci
